theme: jekyll-theme-hacker
title: Nick Nichols
description: [Resume for a Clojurian Web Developer and Dungeon Master]
google_analytics: [UA-127942415-1]

# Name is required
author:
  name: Nick Nichols

twitter:
  username: brainlessmunkey
  card: summary

social:
  name: Nick Nichols
  links:
    - https://twitter.com/brainlessmunkey
    - https://www.linkedin.com/in/nickanichols
    - https://github.com/nnichols

github_username: nnichols
twitter_username: Brainlessmunkey
linkedin_username: nickanichols
stackoverflow_username: 10446899
instagram_username: nickanichols

permalink: /:title/

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
