theme: jekyll-theme-architect
title: Nick Nichols
description: [Clojure Developer and Dungeon Master]
google_analytics: [UA-127942415-1]
repository: nnichols/nnichols.github.io

author:
  name: Nick Nichols

twitter:
  username: brainlessmunkey
  card: summary

social:
  name: Nick Nichols
  links:
    - https://twitter.com/brainlessmunkey
    - https://www.linkedin.com/in/nickanichols
    - https://github.com/nnichols
    - https://www.facebook.com/nick.a.nichols

github_username: nnichols
twitter_username: Brainlessmunkey
linkedin_username: nickanichols
stackoverflow_username: 10446899
instagram_username: nickanichols

permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include: ['_pages','_wiki']
